export default IconLinks = {
    home: require('../../images/icons/home_icon.png'),
    home_selected: require('../../images/icons/home_icon_selected.png'),
    dashboard: require('../../images/icons/dashboard_icon.png'),
    dashboard_selected: require('../../images/icons/dashboard_icon_selected.png'),
    affordability_calc: require('../../images/icons/affordability_calc_icon.png'),
    affordability_calc_selected: require('../../images/icons/affordability_calc_icon_selected.png'),
    browse_property: require('../../images/icons/browse_property.png'),
    browse_property_selected: require('../../images/icons/browse_property_selected.png'),
    more_button: require('../../images/icons/more-button-unselected.png'),
    more_button_selected: require('../../images/icons/more-button-selected.png'),
    ivantage_acc_icon: require('../../images/icons/ivantage_acc_icon.png'),
    current_acc_icon: require('../../images/icons/current_acc_icon.png'),
    diamond: require('../../images/icons/diamond.png'),
    // home_mortgage: require('../../images/icons/home-mortgage.png'),
    gold_bars: require('../../images/icons/gold_bars.png'),
    investment_acc_icon: require('../../images/icons/investment_acc_icon.png'),
    home_mortgage: require('../../images/icons/home-mortgage.png'),
    new_investment: require('../../images/icons/new_investment.png'),
    carbon_add: require('../../images/icons/carbon_add.png'),
    liquidate_deal: require('../../images/icons/liquidate_deal.png'),
    liquidate_partial: require('../../images/icons/partial.png'),
    liquidate_full: require('../../images/icons/full.png'),
    change_password: require('../../images/icons/change_password.png'),
    change_pin: require('../../images/icons/change_pin.png'),
    auto_save: require('../../images/icons/auto_save.png'),
    faq: require('../../images/icons/faq.png'),
}